# Pose visualizations VTTI airport
- colmap results for VTTI airport
- pose estimations, sparse map results

In [2]:
import open3d as o3d
import numpy as np
import plotly.graph_objects as go 
from scipy.spatial.transform import Rotation as R
from colmapParsingUtils import *
import copy

from mpl_toolkits.mplot3d import axes3d
from matplotlib import cm
import matplotlib.pyplot as plt

import cv2

%load_ext autoreload
%autoreload 2
%autosave 180

/home/daniel-choate/miniconda3/envs/py39/lib/python3.9/site-packages/dash/dash.py:23: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, parse_version


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


Autosaving every 180 seconds


In [3]:
# Import colmap files

images_colmap = read_images_text('VTTI_data/HIGH/images.txt')
cameras = read_cameras_text('VTTI_data/HIGH/cameras.txt')
pts3d = read_points3D_text('VTTI_data/HIGH/points3D.txt')

In [4]:
def get_pose_id_mod(id):
    """
    Get the pose transformation for a specific image id
    Input: Image ID
    Output: transform from camera to world coordinates
    """
    # Get quaternion and translation vector
    qvec = images_colmap[id].qvec
    tvec = images_colmap[id].tvec[:,None]
    # print(tvec)
    t = tvec.reshape([3,1])
    # Create rotation matrix
    Rotmat = qvec2rotmat(qvec) # Positive or negative does not matter
    # print("\n Rotation matrix \n", Rotmat)
    # Create 4x4 transformation matrix with rotation and translation
    bottom = np.array([0.0, 0.0, 0.0, 1.0]).reshape([1, 4])
    w2c = np.concatenate([np.concatenate([Rotmat, t], 1), bottom], 0)
    c2w = np.linalg.inv(w2c)
    # self.im_pts_2d[imnum]['w2c'] = w2c
	# self.im_pts_2d[imnum]['c2w'] = c2w
    return w2c, c2w

In [5]:
# Grab all poses 
# print(gnav.images_c)
poses = np.zeros([len(images_colmap),4,4])

for n in range(len(images_colmap)):
    # print(n)
    __, c2w = get_pose_id_mod(n+1)
    # print(c2w)
    poses[n] = c2w

print(poses)

[[[ 9.70824075e-01 -2.67401953e-03  2.39777948e-01 -1.83106892e+00]
  [ 1.15735698e-02  9.99294983e-01 -3.57154023e-02  2.53330977e-01]
  [-2.39513397e-01  3.74484592e-02  9.70170576e-01 -7.64537521e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

 [[ 9.70787698e-01 -2.62551961e-03  2.39925721e-01 -1.78862412e+00]
  [ 1.14922042e-02  9.99301309e-01 -3.55643622e-02  2.47401877e-01]
  [-2.39664712e-01  3.72827207e-02  9.70139590e-01 -7.46580087e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

 [[ 9.70807222e-01  7.78690010e-04  2.39859818e-01 -1.74680332e+00]
  [ 8.27882581e-03  9.99290131e-01 -3.67518045e-02  2.41382698e-01]
  [-2.39718167e-01  3.76646748e-02  9.70111629e-01 -7.28730613e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

 ...

 [[ 9.66813673e-01 -6.07682541e-03  2.55410247e-01  1.13655697e+00]
  [ 1.67784086e-02  9.99069110e-01 -3.97416565e-02 -1.57163148e-01]
  [-2.54930985e-01  4.27081544e-02  

In [6]:
# Grab raw point cloud and rgb data from scene 

raw_pts = [pts3d[key].xyz for key in pts3d.keys()]
raw_rgb = [pts3d[key].rgb for key in pts3d.keys()]
# print(raw_pts)
scene_pts = np.vstack(raw_pts)
scene_rgb = np.vstack(raw_rgb)
# Normalize
scene_rgb = scene_rgb / 255
print(scene_pts)
print(scene_rgb)

[[-0.24535877  0.08603571  0.10389298]
 [ 0.02274476  0.05025617  1.10938148]
 [-0.05640598  0.0966709  -0.18595792]
 ...
 [ 0.08922142  0.07383468  0.38659701]
 [ 0.36328075 -0.55425531  6.60991673]
 [-1.36794796  0.30602502 -5.64403371]]
[[0.24313725 0.29803922 0.09803922]
 [0.5372549  0.48627451 0.41960784]
 [0.8745098  0.68235294 0.44705882]
 ...
 [0.52156863 0.43921569 0.36078431]
 [0.27058824 0.36862745 0.25490196]
 [0.47843137 0.38431373 0.2745098 ]]


In [7]:
print(len(poses))

121


In [8]:
# PLOT INITIAL POINT CLOUD AND POSES 
# Create Open3D visualizer object
vis = o3d.visualization.Visualizer()
vis.create_window(window_name='3D Plot with Pose Axes and Point Cloud')#, width=1000, height=1000)

# Add coordinate axes
axes = o3d.geometry.TriangleMesh.create_coordinate_frame(size=.5)

# loop through poses 
# for pose in poses:
for i in range(len(poses)):
    if (poses[i] == 0).all():
        print("Empty pose", i)
        continue
# for i in range(1):
    # print(i)
    homog_t = poses[i]
    # homog_t = pose
    # print(homog_t)
    s = i*.01
    # print(s)
    # if i in np.arange(106,135):
    if i in np.array([35, 40, 45, 50, 55, 60, 65, 70]):
        axes1 = o3d.geometry.TriangleMesh.create_coordinate_frame(size=.25).transform(homog_t)
        vis.add_geometry(axes1)
    axes1 = o3d.geometry.TriangleMesh.create_coordinate_frame(size=.1).transform(homog_t)
    # axes1 = copy.deepcopy(axes).transform(homog_t)
    vis.add_geometry(axes1)
    
scene_cloud = o3d.geometry.PointCloud()
scene_cloud.points = o3d.utility.Vector3dVector(scene_pts)
scene_cloud.colors = o3d.utility.Vector3dVector(scene_rgb)

vis.add_geometry(axes)
vis.add_geometry(scene_cloud)

# # Size options (jupyter gives issues when running this multiple times, but it looks better)
# render_option = vis.get_render_option()
# render_option.point_size = 1.5


# Run the visualizer
vis.run()
vis.destroy_window()


libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
using driver i915 for 73
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
using driver i915 for 73
pci id for fd 73: 8086:a7a0, driver iris
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
Using DRI3 for screen 0


### FRAMES IN USE: 35, 40, 45, 50, 55, 60, 65, 70

- frame_30850.jpg
- frame_30900.jpg
- frame_30950.jpg
- frame_31000.jpg
- frame_31050.jpg
- frame_31100.jpg
- frame_31150.jpg
- frame_31200.jpg

see <vtti_gnav_demo.ipynb>

In [9]:
print(images_colmap[135].name)

KeyError: 135

In [10]:
for elt in np.array([35, 40, 45, 50, 55, 60, 65, 70]):
    print(images_colmap[elt+1].name)

frame_26149.jpg
frame_26199.jpg
frame_26249.jpg
frame_26299.jpg
frame_26349.jpg
frame_26399.jpg
frame_26449.jpg
frame_26499.jpg


In [35]:
# Determining ground plane points 

# gnd_pts_IDX_old = np.array([525, 532, 533, 534, 538, 539, 6178, 6180, 6188, 6190, 6193, 6192, 5385, 5386, 5388, 5389, 5390, 5391, 5392, 5393])
# ^^Old version doesn't align: likely due to new colmap run

#5000 to 6000
arr2 = np.arange(5385, 5400)
arr1 = np.array([1])
arr3 = np.array([5391, 5392, 5393])
gnd_pts_TEST = np.concatenate((arr1, arr2))

In [19]:
print(len(scene_pts))
print(gnd_pts_TEST)
print(scene_pts[gnd_pts_TEST])

17302
[   1 5385 5386 5387 5388 5389 5390 5391 5392 5393 5394 5395 5396 5397
 5398 5399]
[[ 2.27447641e-02  5.02561687e-02  1.10938148e+00]
 [ 4.33588391e-01  5.76729800e-02  9.52900864e-01]
 [ 2.49225648e-01  4.81976313e-02  1.04066133e+00]
 [ 4.35345235e-01 -2.65640831e-01  6.14523360e+00]
 [ 6.91658220e-02  3.29023813e-02  1.41166851e+00]
 [ 3.69805131e-01 -4.50890827e-01  6.42277987e+00]
 [ 4.65034156e-01  5.54085561e-02  1.01731935e+00]
 [ 1.34184561e+00 -7.48069717e-01  1.44830961e+01]
 [ 1.15967689e+00 -5.84322673e-03  2.08104043e+00]
 [ 2.32636819e-01 -5.54763088e-01  6.11633505e+00]
 [ 1.33643794e-01  4.45119596e-02  1.25365608e+00]
 [ 8.76810431e-02 -4.24409750e-01  6.87414040e+00]
 [ 7.93799362e-01 -1.36317331e-01  6.00165023e+00]
 [ 8.14203701e-01 -4.07135823e-02  3.46279255e+00]
 [ 3.05118240e-01  5.85478327e-02  9.03032063e-01]
 [ 2.12441969e-01 -5.37099829e-01  6.14898395e+00]]


In [17]:
# PLOT INITIAL POINT CLOUD AND POSES 
# Create Open3D visualizer object
vis = o3d.visualization.Visualizer()
vis.create_window(window_name='3D Plot with Pose Axes and Point Cloud')#, width=1000, height=1000)

# Add coordinate axes
axes = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1)

# scene_cloud = o3d.geometry.PointCloud()
# scene_cloud.points = o3d.utility.Vector3dVector(scene_pts)
# scene_cloud.colors = o3d.utility.Vector3dVector(scene_rgb)

# gnd_pts_t = o3d.geometry.PointCloud()
# gnd_pts_t.points = o3d.utility.Vector3dVector(scene_pts[gnd_pts_TEST])
# gnd_pts_t.paint_uniform_color([1,0,0])
# # gnd_pts_t.colors = o3d.utility.Vector3dVector(scene_rgb[gnd_pts_TEST])

gnd_pts = o3d.geometry.PointCloud()
gnd_pts.points = o3d.utility.Vector3dVector(scene_pts[gnd_pts_IDX])
gnd_pts.paint_uniform_color([0,1,0])


vis.add_geometry(axes)
# vis.add_geometry(scene_cloud)
# vis.add_geometry(gnd_pts_t)
vis.add_geometry(gnd_pts)

# # Size options (jupyter gives issues when running this multiple times, but it looks better)
# render_option = vis.get_render_option()
# render_option.point_size = 2


# Run the visualizer
vis.run()
vis.destroy_window()

libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
using driver i915 for 73
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
using driver i915 for 73
pci id for fd 73: 8086:a7a0, driver iris
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
Using DRI3 for screen 0


# USED TO CALCULATE GROUND PLANE POINTS

In [21]:
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(scene_pts)  # (N,3) numpy array

# Optional: voxel downsample for speed
pcd_ds = pcd.voxel_down_sample(voxel_size=0.1)  # tune

# Plane segmentation (RANSAC)
plane_model, inliers = pcd_ds.segment_plane(
    distance_threshold=0.05,  # tune to your noise/scale
    ransac_n=3,
    num_iterations=1000
)

ground_pts = np.asarray(pcd_ds.points)[inliers]

# Pick "a select few"
k = 200
if len(ground_pts) > k:
    idx = np.random.choice(len(ground_pts), k, replace=False)
    ground_pts = ground_pts[idx]

In [30]:
# Build point cloud
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(scene_pts)  # (N,3)

# Downsample for plane estimation
pcd_ds = pcd.voxel_down_sample(voxel_size=0.1)

# Plane segmentation on downsampled cloud
plane_model, _ = pcd_ds.segment_plane(
    distance_threshold=0.05,
    ransac_n=3,
    num_iterations=1000
)

# Unpack plane: ax + by + cz + d = 0
a, b, c, d = plane_model
normal_norm = np.linalg.norm([a, b, c])

# Distance of ALL original points to plane
dist = np.abs(scene_pts @ np.array([a, b, c]) + d) / normal_norm

# Ground mask on FULL cloud
ground_mask = dist < 0.05
ground_idx_scene = np.where(ground_mask)[0]

# Sample indices INTO scene_pts
k = 200
if len(ground_idx_scene) > k:
    idx = np.random.choice(ground_idx_scene, k, replace=False)
else:
    idx = ground_idx_scene

In [31]:
print(idx)

[15183  8096   131 15866  7490 12415 15480 14544 15977   410  9545  4404
  2456 14354  4774 15474 13221  3155  7897  4286  2946 11770 10808 11799
  8827 10857 15780  5977  8731 10360 11532 16106   482  2953  1691 12348
 12749   980 12064  7555  6190  2522   514  1545  5042 10865  9977 14594
  9401  9507 15193  1883 10545 12292  5390   368  2272  6884 12699 10398
  2472  4050 13740 10945 14183  1435 15163 13404   540  5507 15803 14398
  6087 10826 14721  9428 11191  6201 13292  9925  1555  3517  5267 17004
 15625  9216  2798  3824   229  1012  8400   814  8729  9205 13076 16832
  1495 16230  2922  2668  1726 11721  3214 13618 15222 15496 13951 17188
 13315   623 17018  9304  7615   731 10356 10849  9538  5517 10786 13779
  2145 12055 11949  7113  8230  8215  1166 11418  1040 11529  8616  9924
  9272  3203 12391 10369  5148   963 16378 13016  7484   343 12077 10157
  1069  5781  8880 16549  8463   720   945  8296 10342 11457  2066  6081
 16748 12957   513 10607  8079 15035  5022 12754  8

In [36]:
print(idx.max())

17188


In [33]:
# np.save("gnd_idx_VTTI_high.npy", idx)

In [34]:
# PLOT INITIAL POINT CLOUD AND POSES 
# Create Open3D visualizer object
vis = o3d.visualization.Visualizer()
vis.create_window(window_name='3D Plot with Pose Axes and Point Cloud')#, width=1000, height=1000)

# Add coordinate axes
axes = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1)

# scene_cloud = o3d.geometry.PointCloud()
# scene_cloud.points = o3d.utility.Vector3dVector(scene_pts)
# scene_cloud.colors = o3d.utility.Vector3dVector(scene_rgb)

# gnd_pts_t = o3d.geometry.PointCloud()
# gnd_pts_t.points = o3d.utility.Vector3dVector(scene_pts[gnd_pts_TEST])
# gnd_pts_t.paint_uniform_color([1,0,0])
# # gnd_pts_t.colors = o3d.utility.Vector3dVector(scene_rgb[gnd_pts_TEST])

gnd_pts = o3d.geometry.PointCloud()
gnd_pts.points = o3d.utility.Vector3dVector(scene_pts[idx])
gnd_pts.paint_uniform_color([0,1,0])


vis.add_geometry(axes)
# vis.add_geometry(scene_cloud)
# vis.add_geometry(gnd_pts_t)
vis.add_geometry(gnd_pts)

# # Size options (jupyter gives issues when running this multiple times, but it looks better)
# render_option = vis.get_render_option()
# render_option.point_size = 2


# Run the visualizer
vis.run()
vis.destroy_window()

libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
using driver i915 for 73
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
using driver i915 for 73
pci id for fd 73: 8086:a7a0, driver iris
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
Using DRI3 for screen 0


In [ ]:
# # GIF HELP

# # Capture frames for GIF
# frames = []
# num_frames = 30  # Adjust the number of frames
# angle_step = 180/num_frames


# for i in range(num_frames):
# 	# Rotate the view
#     view_control.rotate(angle_step, 0)  # (horizontal, vertical)

#     # vis.update_geometry(axis_orig) # Only if I move it myself?
#     vis.poll_events()
#     vis.update_renderer()

#     # Capture frame directly into memory
#     image = vis.capture_screen_float_buffer(False)
#     image_8bit = (np.asarray(image) * 255).astype(np.uint8)  # Convert to 8-bit
#     frames.append(image_8bit)


# for i in range(num_frames):
# 	# Rotate the view
# 	view_control.rotate(angle_step, 0)  # (horizontal, vertical)

# 	# vis.update_geometry(axis_orig) # Only if I move it myself?
# 	vis.poll_events()
# 	vis.update_renderer()

# 	# Capture frame directly into memory
# 	image = vis.capture_screen_float_buffer(False)
# 	image_8bit = (np.asarray(image) * 255).astype(np.uint8)  # Convert to 8-bit
# 	frames.append(image_8bit)

# for i in range(num_frames):
# 	# Rotate the view
# 	view_control.rotate(angle_step, 0)  # (horizontal, vertical)

# 	# vis.update_geometry(axis_orig) # Only if I move it myself?
# 	vis.poll_events()
# 	vis.update_renderer()

# 	# Capture frame directly into memory
# 	image = vis.capture_screen_float_buffer(False)
# 	image_8bit = (np.asarray(image) * 255).astype(np.uint8)  # Convert to 8-bit
# 	frames.append(image_8bit)

# for i in range(num_frames):
# 	# Rotate the view
# 	view_control.rotate(angle_step, angle_step/5)  # (horizontal, vertical)

# 	# vis.update_geometry(axis_orig) # Only if I move it myself?
# 	vis.poll_events()
# 	vis.update_renderer()

# 	# Capture frame directly into memory
# 	image = vis.capture_screen_float_buffer(False)
# 	image_8bit = (np.asarray(image) * 255).astype(np.uint8)  # Convert to 8-bit
# 	frames.append(image_8bit)

# for i in range(num_frames):
# 	# Rotate the view
#     view_control.rotate(-angle_step, -angle_step/5)  # (horizontal, vertical)

#     # vis.update_geometry(axis_orig) # Only if I move it myself?
#     vis.poll_events()
#     vis.update_renderer()

#     # Capture frame directly into memory
#     image = vis.capture_screen_float_buffer(False)
#     image_8bit = (np.asarray(image) * 255).astype(np.uint8)  # Convert to 8-bit
#     frames.append(image_8bit)


# for i in range(num_frames):
# 	# Rotate the view
# 	view_control.rotate(-angle_step, 0)  # (horizontal, vertical)

# 	# vis.update_geometry(axis_orig) # Only if I move it myself?
# 	vis.poll_events()
# 	vis.update_renderer()

# 	# Capture frame directly into memory
# 	image = vis.capture_screen_float_buffer(False)
# 	image_8bit = (np.asarray(image) * 255).astype(np.uint8)  # Convert to 8-bit
# 	frames.append(image_8bit)

# for i in range(num_frames):
# 	# Rotate the view
# 	view_control.rotate(-angle_step, 0)  # (horizontal, vertical)

# 	# vis.update_geometry(axis_orig) # Only if I move it myself?
# 	vis.poll_events()
# 	vis.update_renderer()

# 	# Capture frame directly into memory
# 	image = vis.capture_screen_float_buffer(False)
# 	image_8bit = (np.asarray(image) * 255).astype(np.uint8)  # Convert to 8-bit
# 	frames.append(image_8bit)

# for i in range(num_frames):
# 	# Rotate the view
# 	view_control.rotate(-angle_step, 0)  # (horizontal, vertical)

# 	# vis.update_geometry(axis_orig) # Only if I move it myself?
# 	vis.poll_events()
# 	vis.update_renderer()

# 	# Capture frame directly into memory
# 	image = vis.capture_screen_float_buffer(False)
# 	image_8bit = (np.asarray(image) * 255).astype(np.uint8)  # Convert to 8-bit
# 	frames.append(image_8bit)

# # Create GIF
# # Ensure frames are in the correct format
# frames = [frame.astype("uint8") for frame in frames]

# # Use imageio to save as GIF
# imageio.mimsave("test.gif", frames, fps=30, loop=0)  # Adjust fps if necessary