# GIF CREATION FOR Ground Navigation for Aerial Vehicles

With a satellite reference image, we intend to utilize a SfM solution to match ground segments of images to the reference map.
- Inputs: Reference image (satellite), SfM solution (images, points, cameras), selected images (5)
- Output: Correction solutions for translation, rotation, scaling

In [1]:
import numpy as np
import cv2
import open3d as o3d
import plotly.graph_objects as go
import plotly.io as pio
from scipy.spatial.transform import Rotation as R
from scipy.spatial import cKDTree
import imageio
import time
# %matplotlib qt
import matplotlib.pyplot as plt
from matplotlib.path import Path

from groundNAV_agent import *
from colmapParsingUtils import *

# SAVE YOUR WORK
%load_ext autoreload
%autoreload 2
%autosave 180

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


Autosaving every 180 seconds


In [2]:
# # Load in necessary parameters for gNAV agent 
# # Define Class Parameters 

# images_colm  = "/home/daniel-choate/ASAR/s2/TerrainNav/TTurf/test/images.txt"
# cameras_colm = "/home/daniel-choate/ASAR/s2/TerrainNav/TTurf/test/cameras.txt"
# pts3d_colm = "/home/daniel-choate/ASAR/s2/TerrainNav/TTurf/test/points3D_f.txt"

# # Images selected for local corrections
# image_1 = "/home/daniel-choate/Datasets/COLMAP/TTurfSAT/TTurf_Im/IMG_9446.JPEG" #ID:4
# image_2 = "/home/daniel-choate/Datasets/COLMAP/TTurfSAT/TTurf_Im/IMG_9520.JPEG" #ID:78
# image_3 = "/home/daniel-choate/Datasets/COLMAP/TTurfSAT/TTurf_Im/IMG_9531.JPEG" #ID:89
# image_4 = "/home/daniel-choate/Datasets/COLMAP/TTurfSAT/TTurf_Im/IMG_9542.JPEG" #ID:100
# image_5 = "/home/daniel-choate/Datasets/COLMAP/TTurfSAT/TTurf_Im/IMG_9576.JPEG" #ID:134
# # Load in satellite reference image
# sat_ref = "TTurf/TurfSat.jpg"
# # sat_ref = cv2.imread('TTurf/TurfSat.jpg')

# # Organize for agent params
# images = [image_1, image_2, image_3, image_4, image_5]

In [3]:
# CLOSER IMAGES 
# Load in necessary parameters for gNAV agent 
# Define Class Parameters 

images_colm  = "/home/daniel-choate/ASAR/s2/TerrainNav/TTurf/test/images.txt"
cameras_colm = "/home/daniel-choate/ASAR/s2/TerrainNav/TTurf/test/cameras.txt"
pts3d_colm = "/home/daniel-choate/ASAR/s2/TerrainNav/TTurf/test/points3D_f.txt"

# Images selected for local corrections
# image_1 = "/home/daniel-choate/Datasets/COLMAP/TTurfSAT/TTurf_Im/IMG_9449.JPEG"
image_1 = "/home/daniel-choate/Datasets/COLMAP/TTurfSAT/TTurf_Im/IMG_9475.JPEG"
# image_2 = "/home/daniel-choate/Datasets/COLMAP/TTurfSAT/TTurf_Im/IMG_9459.JPEG"
image_2 = "/home/daniel-choate/Datasets/COLMAP/TTurfSAT/TTurf_Im/IMG_9464.JPEG"
image_3 = "/home/daniel-choate/Datasets/COLMAP/TTurfSAT/TTurf_Im/IMG_9467.JPEG"
image_4 = "/home/daniel-choate/Datasets/COLMAP/TTurfSAT/TTurf_Im/IMG_9473.JPEG"
image_5 = "/home/daniel-choate/Datasets/COLMAP/TTurfSAT/TTurf_Im/IMG_9476.JPEG"
# Load in satellite reference image
sat_ref = "TTurf/TurfSat.jpg"
# sat_ref = cv2.imread('TTurf/TurfSat.jpg')

# Organize for agent params
images = [image_1, image_2, image_3, image_4, image_5]

In [4]:
# Create class
gnav = gNAV_agent(images_colm, cameras_colm, pts3d_colm, images, sat_ref)

# Grab raw points and RGB data for scene and reference cloud
scene_pts, rgb_data = gnav.grab_pts(gnav.pts3d_c)
ref_pts, ref_rgb = gnav.ref_pts, gnav.ref_rgb

### Changing REF FRAME TO MIDDLE

In [5]:
# Use ground plane pts to set reference frame 
# Need gravity and height
pts_gnd_idx = np.array([25440, 25450, 25441, 25449, 25442, 25445, 103922, 103921, 103919, 103920])
# tform_ref_frame = gnav.set_ref_frame(pts_gnd_idx) # THIS IS WHAT I AM CHANGING 
tform_ref_frame = gnav.set_ref_frame_mid(pts_gnd_idx) # NEW VERSION
tform_ref_frame_pts = gnav.inv_homog_transform(tform_ref_frame)
print("\nReference frame transformation\n", tform_ref_frame_pts)


Reference frame transformation
 [[-1.55069060e-03  9.81197008e-01  1.93002661e-01 -1.21025836e-01]
 [-1.42845166e-01 -1.91240997e-01  9.71093270e-01  1.86102525e+00]
 [ 9.89743833e-01 -2.60636319e-02  1.40455805e-01  7.28134156e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [6]:
# Transform all points to the new coordinate system 
# Not necessary since we aren't using the cloud, but a good visual check for coord frame
tform_ref_frame_inv = gnav.inv_homog_transform(tform_ref_frame)
origin_ref, scene_pts_ref, scene_vec_ref = gnav.unit_vec_tform(scene_pts, gnav.origin_w, tform_ref_frame_inv)
# print(origin_ref)
# Transform scene cloud to 2D (also as a visual check)
# Note: 2d projection will look off with z=-1; see TTurf_v2 for cropping method
scene_ref_2d = gnav.proj_2d_scene(scene_pts_ref)
# print(scene_ref_2d)

In [7]:
# Image 1 - OS in Jumbos OR top half of S

# # OS in Jumbos 
# imnum = 0
# # x,y = 150,1725
# # side_x = 2250 # WIDTH
# # side_y = 750 # HEIGHT
# x,y = 150, 2000
# side_x = 1500
# side_y = 250 # HEIGHT

# # Top half of S
# imnum = 0
# x,y = 300,2100
# side_x = 1300 # WIDTH
# side_y = 750 # HEIGHT
# x,y = 300,2200
# side_x = 1300 # WIDTH
# side_y = 600 # HEIGHT

# # Bottom of M 
# imnum = 0
# x,y = 1100,2000
# side_x = 1300 # WIDTH
# side_y = 600 # HEIGHT

# # 10 yd hash 
imnum = 0
x,y = 1500,1000
side_x = 900 # WIDTH
side_y = 500 # HEIGHT

# Plot to visualize
# gnav.plot_rect_im(x, y, side_x, side_y, imnum) 

# Get necessary location and rgb data 
pts_loc, pts_rgb = gnav.grab_image_pts(x, y, side_x, side_y, imnum)
# print(pts_loc)
# print(pts_rgb)

In [8]:
# Image 2 - 40yd (far), OR O in jumbos

# # 40yd (far)
# imnum = 1
# x,y = 1150,1150
# side_x = 1100 # WIDTH
# side_y = 900 # HEIGHT

# # O in jumbos 
# imnum = 1
# x,y = 300,1700
# side_x = 1000 # WIDTH
# side_y = 900 # HEIGHT

# Bottom of S
imnum = 1
x,y = 1400,2300
side_x = 800 # WIDTH
side_y = 1200 # HEIGHT

# Plot to visualize
# gnav.plot_rect_im(x, y, side_x, side_y, imnum) 

# Get necessary location and rgb data 
pts_loc, pts_rgb = gnav.grab_image_pts(x, y, side_x, side_y, imnum)
# print(pts_rgb)

In [9]:
# Image 3 - Jumbo logo OR B in jumbos

# # Jumbo logo
# imnum = 2
# x,y = 400,1500
# side_x = 1500 # WIDTH
# side_y = 750 # HEIGHT

# B in jumbos 
imnum = 2
x,y = 800,2100
side_x = 1400 # WIDTH
side_y = 500 # HEIGHT

# Plot to visualize
# gnav.plot_rect_im(x, y, side_x, side_y, imnum) 

# Get necessary location and rgb data 
pts_loc, pts_rgb = gnav.grab_image_pts(x, y, side_x, side_y, imnum)
# print(pts_rgb)

In [10]:
# Image 4 - 30yd (near) OR edge to endzone 

# 30yd (near)
# imnum = 3
# x,y = 1350,1450
# side_x = 1200 # WIDTH
# side_y = 500 # HEIGHT

# Edge to endzone
imnum = 3
x,y = 1150,900
side_x = 1200 # WIDTH
side_y = 500 # HEIGHT

# Plot to visualize
# gnav.plot_rect_im(x, y, side_x, side_y, imnum) 

# Get necessary location and rgb data 
pts_loc, pts_rgb = gnav.grab_image_pts(x, y, side_x, side_y, imnum)
# print(pts_rgb)

In [11]:
# Image 5 - 10yd marker
imnum = 4
x,y = 1200,1300
side_x = 1000 # WIDTH
side_y = 700 # HEIGHT

# Plot to visualize
# gnav.plot_rect_im(x, y, side_x, side_y, imnum) 

# Get necessary location and rgb data 
pts_loc, pts_rgb = gnav.grab_image_pts(x, y, side_x, side_y, imnum)
# print(pts_rgb)

In [12]:
# Generate projection of image sections 
for i in range(len(images)):
# Just for the first image for now
# for i in range(1):
    # Unit vectors in camera coords 
    pts_vec_c, pts_rgb_gnd = gnav.unit_vec_c(i)
    gnav.im_mosaic[i] = {'rgbc': pts_rgb_gnd}

    # Get transformation matrix that move from camera coords to world coords
    id = gnav.im_ids[i]
    homog_w2c, homog_c2w = gnav.get_pose_id(id,i)
    # print('Homogeneous transformation from world to camera \n', homog_c2w)
    # print('\n Homogeneous transformation from camera to world \n', homog_w2c)

    # Transform to world coords
    origin_c, pts_loc_w, pts_vec_w = gnav.unit_vec_tform(pts_vec_c, gnav.origin_w, homog_c2w)
    # print('\n New camera frame origin = ', origin_c)
    
    # Get new points 
    ranges, new_pts_w = gnav.pt_range(pts_vec_w, homog_c2w, origin_c, i)
    # print('\nNew Points \n', new_pts_w)

    # Transfer points to reference frame
    __, new_pts_r, pts_vec_r = gnav.unit_vec_tform(new_pts_w, gnav.origin_w, tform_ref_frame_pts)

    # Convert points to grayscale 
    gray_c = gnav.conv_to_gray(gnav.im_mosaic[i]['rgbc'],i)
    # print(gray_c)

    # Put new points and grayscale colors in image mosaic
    gnav.im_mosaic[i]['pts'] = new_pts_r
    gnav.im_mosaic[i]['color_g'] = gray_c
    
    print("\nDone image ", i)


Done image  0

Done image  1

Done image  2

Done image  3

Done image  4


In [13]:
# OLD GUESSES 


# scale = 87 # Avg guess OLD IMAGES
# scale = 80 # Decent average guess - Old frame, new ims

# # Avg guess for OLD IMAGES  
# x = 294
# y = 172
# yaw = np.deg2rad(1)

# # Going for average guess - new images!, old frame
# x = 331
# y = 264
# yaw = np.deg2rad(-1)
# # Corrected guess (just for 10yd line)! 
# x = 333
# y = 260
# yaw = np.deg2rad(-1)

In [14]:
# Implementing an initial guess for the local image 

# SCALE for initial guess 
# scale = gnav.focal/39
scale = 80

# Avg guess for OLD IMAGES  
# x = -55
# y = 20
# yaw = np.deg2rad(140)
x = -45
y = 10
yaw = np.deg2rad(140)

# # AFTER 8 iterations
# scale = 79.98806916
# yaw = 2.4459095
# x = -55.5029947
# y = 21.33034606


tform_guess = gnav.tform_create(x,y,0,0,0,yaw)
gnav.best_guess_tform = tform_guess
gnav.best_guess_scale = scale
# print(tform_guess)

for i in range(len(images)):
# Just for the first image for now
# for i in range(1):
    loc_im_pts = gnav.im_mosaic[i]['pts'].copy()
    # print(loc_im_pts)
    loc_im_pts[:, :2] *= scale
    # Get new points 
    __, loc_im_pts_guess, loc_im_vec_guess = gnav.unit_vec_tform(loc_im_pts, gnav.origin_w, tform_guess)
    gnav.im_pts_best_guess[i] = {'pts': loc_im_pts_guess}
    # gnav.im_pts_best_guess[i]['tree'] = cKDTree(loc_im_pts_guess) # UNECESSARY 

    print("\nDone image ", i)


Done image  0

Done image  1

Done image  2

Done image  3

Done image  4


In [15]:
# PLOTTING THE NEW SCENE MOSAIC

# Use open3d to create point cloud visualization 
# Create visualization 
vis = o3d.visualization.Visualizer()
vis.create_window(window_name="Mosaic scene with satellite reference")

# Create axes @ origin
axis_origin = o3d.geometry.TriangleMesh.create_coordinate_frame(size=40)

# Create point cloud for image points
im0_cloud = o3d.geometry.PointCloud()
im0_cloud.points = o3d.utility.Vector3dVector(gnav.im_pts_best_guess[0]['pts'])
im0_cloud.colors = o3d.utility.Vector3dVector(gnav.im_mosaic[0]['color_g'])

# Create point cloud for image points
im1_cloud = o3d.geometry.PointCloud()
im1_cloud.points = o3d.utility.Vector3dVector(gnav.im_pts_best_guess[1]['pts'])
im1_cloud.colors = o3d.utility.Vector3dVector(gnav.im_mosaic[1]['color_g'])

# Create point cloud for image points
im2_cloud = o3d.geometry.PointCloud()
im2_cloud.points = o3d.utility.Vector3dVector(gnav.im_pts_best_guess[2]['pts'])
im2_cloud.colors = o3d.utility.Vector3dVector(gnav.im_mosaic[2]['color_g'])

# Create point cloud for image points
im3_cloud = o3d.geometry.PointCloud()
im3_cloud.points = o3d.utility.Vector3dVector(gnav.im_pts_best_guess[3]['pts'])
im3_cloud.colors = o3d.utility.Vector3dVector(gnav.im_mosaic[3]['color_g'])

# Create point cloud for image points
im4_cloud = o3d.geometry.PointCloud()
im4_cloud.points = o3d.utility.Vector3dVector(gnav.im_pts_best_guess[4]['pts'])
im4_cloud.colors = o3d.utility.Vector3dVector(gnav.im_mosaic[4]['color_g'])

# Create point cloud for reference cloud (satellite)
ref_cloud = o3d.geometry.PointCloud()
ref_cloud.points = o3d.utility.Vector3dVector(gnav.ref_pts)
ref_cloud.colors = o3d.utility.Vector3dVector(gnav.ref_rgb)

# Add necessary geometries to visualization 
vis.add_geometry(axis_origin)
vis.add_geometry(ref_cloud)
vis.add_geometry(im0_cloud)
vis.add_geometry(im1_cloud)
vis.add_geometry(im2_cloud)
vis.add_geometry(im3_cloud)
vis.add_geometry(im4_cloud)

idxs = {}
# # Create an edge surrounding each of the images 
for imnum in range(len(images)):
    # imb = o3d.geometry.PointCloud()
    # Grab corners
    corners = gnav.im_pts_2d[imnum]['corners']
    print(corners)
    # Corner indices
    idxs[imnum] = [0, -corners[2], -1, corners[2]-1]
    print(idxs[imnum])
    # Corner points
    points = np.array(gnav.im_pts_best_guess[imnum]['pts'])[idxs[imnum]]
    points += np.array([0,0,-.5])
    print(points)
    lines = [[0,1], [1,2], [2,3], [3,0]]

    line_set = o3d.geometry.LineSet()
    line_set.points = o3d.utility.Vector3dVector(points)
    line_set.lines = o3d.utility.Vector2iVector(lines)
    line_set.colors = o3d.utility.Vector3dVector([[1,0,0] for _ in lines])  # green
    vis.add_geometry(line_set)
    



# # Size options (jupyter gives issues when running this multiple times, but it looks better)
render_option = vis.get_render_option()
render_option.line_width = 100
# render_option.point_size = 2

# Set up initial viewpoint
view_control = vis.get_view_control()
# Direction which the camera is looking
view_control.set_front([0, 0.01, -1])  # Set the camera facing direction
# Point which the camera revolves about 
view_control.set_lookat([0, 0, 0])   # Set the focus point
# Defines which way is up in the camera perspective 
view_control.set_up([0, -1, 0])       # Set the up direction
view_control.set_zoom(.45)           # Adjust zoom if necessary




# Run and destroy visualization 
# vis.run()
vis.poll_events()
vis.update_renderer()
vis.capture_screen_image("Figs_gifs/Mapgifs/June10_PAPERtest/screenshot_8.png")
time.sleep(1.5)  # Keep window open for 1.5 seconds
vis.destroy_window()
# vis.destroy_window()


libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
using driver i915 for 74
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
using driver i915 for 74
pci id for fd 74: 8086:a7a0, driver iris
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
Using DRI3 for screen 0


[1500 1000  900  500]
[0, -900, -1, 899]
[[-76.49854399 -76.62296644   0.50111726]
 [-41.4459725  -47.77351022   0.50111726]
 [-29.85699796 -59.99534219   0.50111726]
 [-56.00014744 -95.97110831   0.50111726]]
[1400 2300  800 1200]
[0, -800, -1, 799]
[[ 9.49357571 44.8647279   0.50111726]
 [55.07039588 54.53759154  0.50111726]
 [57.47487749 46.72369062  0.50111726]
 [17.03976436 26.25588295  0.50111726]]
[ 800 2100 1400  500]
[0, -1400, -1, 1399]
[[  27.68927021 -107.17433168    0.50111726]
 [  36.59306419  -40.64982559    0.50111726]
 [  65.93325832  -36.62630408    0.50111726]
 [  86.06967087  -96.83761823    0.50111726]]
[1150  900 1200  500]
[0, -1200, -1, 1199]
[[ -7.39603011 -90.24273788   0.50111726]
 [ -3.51454701 -60.65579313   0.50111726]
 [ 16.03652824 -61.1469683    0.50111726]
 [ 21.82278207 -90.84639571   0.50111726]]
[1200 1300 1000  700]
[0, -1000, -1, 999]
[[-135.72163988  153.28723784    0.50111726]
 [ -59.09529365   49.14098459    0.50111726]
 [ -72.89641025   33.897

### SSD Process (using original version)

In [16]:
# n = 5
# for imnum in range(len(images)):
# # Just for the first image for now 
# # for imnum in range(1):
# # for imnum in range(4, 5, 1):
#     ssds = gnav.ssd_nxn(n, imnum)
#     gnav.ssds_curr[imnum] = ssds
# print("Done, most recent SSDs are\n", ssds)

In [17]:
# # NEW new LOOKUP STRATEGY - SHOULD BE FASTER - NOT WORKING (yet)
# n = 5
# for imnum in range(len(images)):
# # Just for the first image for now 
# # for imnum in range(1):
#     ssds1 = gnav.ssd_nxn_NEWnew(n, imnum)
#     gnav.ssds1_curr[imnum] = ssds1
# print("Done, SSDs are\n", ssds1)

# Least Square Process

### Create a vector for each SSD

### Full Lsquares 

In [18]:
# Initial guess parameters
# INITIAL GUESS Parameters
# s = 1
# theta = np.deg2rad(0)
# tp = 0
# tq = 0
s = scale
theta = yaw
tp = x
tq = y
params = np.array([s, theta, tp, tq]).reshape(4,1)
init_guess = np.array([s, theta, tp, tq]).reshape(4,1)
print("\nInitial Guess parameters\n", params)


Initial Guess parameters
 [[ 79.98806916]
 [  2.4459095 ]
 [-55.5029947 ]
 [ 21.33034606]]


In [19]:
iterations = 10
n = 5

viss = {}

# for iter_idx in range(5,10):
for iter_idx in range(iterations):
    # Loop through full set of images
    for imnum in range(len(images)):
        ssds = gnav.ssd_nxn(n, imnum)
        gnav.ssds_curr[imnum] = ssds
    # print("Most recent SSDs\n", ssds)
    

    
    
    # Create a vector from the original position to the minimum SSD location 
    cor_vecs = np.zeros((len(images), 2))
    base_vec = np.zeros((len(images), 2))
    for im_cv in range(len(images)):
    # for imnum in range(1):
        # Grab SSDs - get id of minimum
        ssds = gnav.ssds_curr[im_cv]
        # print(f"\nSSDS for image {i}\n", ssds)
        idrow, idcol = np.unravel_index(np.argmin(ssds), ssds.shape)
        # print("\nidrow, idcol\n", idrow, idcol)
        # Define best shift vector 
        shiftx_min = idrow-n
        shifty_min = idcol-n
        print("\nBEST SHIFT VECTOR = ", shiftx_min, shifty_min)
        print(f"\nBEST SSD for image {im_cv} = ", ssds[idrow, idcol])
        cor_vecs[im_cv] = shiftx_min, shifty_min
        # Get mean of satellite points for base of x and y
        sat_pts, __ = gnav.get_inside_sat_pts(im_cv, 0,0)#shiftx_min, shifty_min)
        # print("\nInside satellite points\n", sat_pts)
        basex, basey = np.mean(sat_pts[:,0]), np.mean(sat_pts[:,1])
        # print("\nBase of x and y = ", basex, basey)
        base_vec[im_cv] = basex, basey
    
    print("\nCorrection vectors:\n", cor_vecs)
    print("\nBase of correction vectors: \n", base_vec)
    
    points_b = np.hstack((base_vec, np.zeros((len(images), 1))))
    points_e = points_b + np.hstack((cor_vecs, np.zeros((len(images),1))))
    points = np.vstack((points_b, points_e))
    # print("\nBeginning of points: \n", points_b)
    # print("\nEnd of points: \n",points_e)
    # print("\nAll points: \n",points)
    lines = []
    for lin in range(len(images)):
        lines.append([lin,lin+len(images)])
        # print(lin, lin+len(images))
    
    # print("\nLines for OPEN3d:\n",lines)
    
    # Delta y term
    # print(cor_vecs.reshape(-1,1))
    yi = cor_vecs.reshape(-1,1)
    print("\nYi\n", yi)
    
    
    
    
    
    # Form jacobian for each image
    J = np.zeros((2*len(images),4))
    theta = params[1][0]
    s = params[0][0]
    # print(J)
    for i_m in range(len(images)):
        xpi = np.mean(gnav.im_pts_best_guess[i_m]['pts'][:,0])
        xqi = np.mean(gnav.im_pts_best_guess[i_m]['pts'][:,1])
        # print(xpi, xqi)
        # Jacobian values (2x4)
        j11 = np.cos(theta)*xpi - np.sin(theta)*xqi
        j21 = np.sin(theta)*xpi + np.cos(theta)*xqi
        j12 = -params[0][0]*(np.sin(theta)*xpi + np.cos(theta)*xqi)
        j22 = params[0][0]*(np.cos(theta)*xpi - np.sin(theta)*xqi)
        j13, j23, j14, j24 = 1, 0, 0, 1
        # print(j13)
    
        # Construct Jacobian 
        J_upper = np.hstack((j11, j12, j13, j14))  # First row block (y_p terms)
        # print("\nJ Upper\n", J_upper)
        J_lower = np.hstack((j21, j22, j23, j24))  # Second row block (y_q terms)
        # print("\nJ Lower\n", J_lower)
        j = np.vstack((J_upper, J_lower))  # Shape (2N, 4)
        print("\nJacobian\n", j)
        J[2*(i_m):2*(i_m)+2, :] = j
    
    print("\nJACOBIAN\n", J)
    # print("\nJacobian shape: ", J.shape)
    
    # Least squares process
    JTJi = np.linalg.inv(J.T@J)
    Dalpha = JTJi@J.T@yi
    print("\nDelta Alpha:\n", Dalpha)
    
    
    
    params += Dalpha
    print("\nUpdated Params: scale, theta, tq, tp\n", params)
    
    
    
    # Apply change
    tform_mat = gnav.tform_create(params[2][0], params[3][0], 0, 0, 0, params[1][0]) # x,y,z,roll,pitch,yaw
    print("\nTransformation matrix\n", tform_mat)
    
    
    for i_c in range(len(images)):
    # Just for the first image for now
    # for i in range(1):
        loc_im_pts = gnav.im_mosaic[i_c]['pts'].copy()
        # print(loc_im_pts)
        loc_im_pts[:, :2] *= params[0][0].astype(np.float64)
        # Get new points 
        __, loc_im_pts_NEW, __ = gnav.unit_vec_tform(loc_im_pts, gnav.origin_w, tform_mat)
        gnav.im_pts_best_guess[i_c]['pts'] = loc_im_pts_NEW
        # gnav.im_pts_best_guess[i]['tree'] = cKDTree(loc_im_pts_guess) # UNECESSARY 
    
        # print("\nDone image ", i)








    # PLOT NEWEST GUESS 
    globals()[f"vis_{iter_idx}"] = o3d.visualization.Visualizer()
    globals()[f"vis_{iter_idx}"].create_window(window_name="Mosaic scene with satellite reference")
    
    # Create axes @ origin
    axis_origin = o3d.geometry.TriangleMesh.create_coordinate_frame(size=40)
    
    # Create point cloud for image points
    im0_cloud = o3d.geometry.PointCloud()
    im0_cloud.points = o3d.utility.Vector3dVector(gnav.im_pts_best_guess[0]['pts'])
    im0_cloud.colors = o3d.utility.Vector3dVector(gnav.im_mosaic[0]['color_g'])
    
    # Create point cloud for image points
    im1_cloud = o3d.geometry.PointCloud()
    im1_cloud.points = o3d.utility.Vector3dVector(gnav.im_pts_best_guess[1]['pts'])
    im1_cloud.colors = o3d.utility.Vector3dVector(gnav.im_mosaic[1]['color_g'])
    
    # Create point cloud for image points
    im2_cloud = o3d.geometry.PointCloud()
    im2_cloud.points = o3d.utility.Vector3dVector(gnav.im_pts_best_guess[2]['pts'])
    im2_cloud.colors = o3d.utility.Vector3dVector(gnav.im_mosaic[2]['color_g'])
    
    # Create point cloud for image points
    im3_cloud = o3d.geometry.PointCloud()
    im3_cloud.points = o3d.utility.Vector3dVector(gnav.im_pts_best_guess[3]['pts'])
    im3_cloud.colors = o3d.utility.Vector3dVector(gnav.im_mosaic[3]['color_g'])
    
    # Create point cloud for image points
    im4_cloud = o3d.geometry.PointCloud()
    im4_cloud.points = o3d.utility.Vector3dVector(gnav.im_pts_best_guess[4]['pts'])
    im4_cloud.colors = o3d.utility.Vector3dVector(gnav.im_mosaic[4]['color_g'])
    
    # Create point cloud for reference cloud (satellite)
    ref_cloud = o3d.geometry.PointCloud()
    ref_cloud.points = o3d.utility.Vector3dVector(gnav.ref_pts)
    ref_cloud.colors = o3d.utility.Vector3dVector(gnav.ref_rgb)
    
    # Add necessary geometries to visualization 
    globals()[f"vis_{iter_idx}"].add_geometry(axis_origin)
    globals()[f"vis_{iter_idx}"].add_geometry(im0_cloud)
    globals()[f"vis_{iter_idx}"].add_geometry(im1_cloud)
    globals()[f"vis_{iter_idx}"].add_geometry(im2_cloud)
    globals()[f"vis_{iter_idx}"].add_geometry(im3_cloud)
    globals()[f"vis_{iter_idx}"].add_geometry(im4_cloud)
    globals()[f"vis_{iter_idx}"].add_geometry(ref_cloud)

    # # Create an edge surrounding each of the images 
    for imi in range(len(images)):
        # imb = o3d.geometry.PointCloud()
        # Grab corners
        # corners = gnav.im_pts_2d[imi]['corners']
        # print(corners)
        # Corner indices
        # idxs = [0, -corners[2], -1, corners[2]-1]
        # print(idxs)
        # Corner points
        points = np.array(gnav.im_pts_best_guess[imi]['pts'])[idxs[imi]]
        # points_trans = points.copy()
        # __, points_new, __ = gnav.unit_vec_tform(points_trans, gnav.origin_w, tform_mat)
        points += np.array([0,0,-.5])
        # print(points)
        lines = [[0,1], [1,2], [2,3], [3,0]]
    
        line_set = o3d.geometry.LineSet()
        line_set.points = o3d.utility.Vector3dVector(points)
        line_set.lines = o3d.utility.Vector2iVector(lines)
        line_set.colors = o3d.utility.Vector3dVector([[1,0,0] for _ in lines])  # green
        globals()[f"vis_{iter_idx}"].add_geometry(line_set)
    
    # # Size options (jupyter gives issues when running this multiple times, but it looks better)
    # render_option = vis.get_render_option()
    # render_option.point_size = 2

    # Set up initial viewpoint
    view_control = globals()[f"vis_{iter_idx}"].get_view_control()
    # Direction which the camera is looking
    view_control.set_front([0, 0.01, -1])  # Set the camera facing direction
    # Point which the camera revolves about 
    view_control.set_lookat([0, 0, 0])   # Set the focus point
    # Defines which way is up in the camera perspective 
    view_control.set_up([0, -1, 0])       # Set the up direction
    view_control.set_zoom(.45)           # Adjust zoom if necessary

    # viss[iter_idx] = globals()[f"vis_{iter_idx}"]
    # Run and destroy visualization 
    # vis.run()
    globals()[f"vis_{iter_idx}"].poll_events()
    globals()[f"vis_{iter_idx}"].update_renderer()
    globals()[f"vis_{iter_idx}"].capture_screen_image(f"Figs_gifs/Mapgifs/June10_PAPERtest/screenshot_{iter_idx+1}.png")
    time.sleep(1.5)  # Keep window open for 1.5 seconds
    globals()[f"vis_{iter_idx}"].destroy_window()    
    


Number of points used for image 0:  (1004,)
Number of points used for image 1:  (649,)
Number of points used for image 2:  (2824,)
Number of points used for image 3:  (723,)
Number of points used for image 4:  (4746,)

BEST SHIFT VECTOR =  2 4

BEST SSD for image 0 =  23.80763963312673

BEST SHIFT VECTOR =  -3 -5

BEST SSD for image 1 =  16.502390986994207

BEST SHIFT VECTOR =  -1 1

BEST SSD for image 2 =  121.29586913918843

BEST SHIFT VECTOR =  -1 2

BEST SSD for image 3 =  11.741553333479576

BEST SHIFT VECTOR =  5 2

BEST SSD for image 4 =  60.42751853255075

Correction vectors:
 [[ 2.  4.]
 [-3. -5.]
 [-1.  1.]
 [-1.  2.]
 [ 5.  2.]]

Base of correction vectors: 
 [[ -52.2559761   -71.44223108]
 [  31.84899846   42.05701079]
 [  54.33002833  -73.83498584]
 [   6.65698479  -76.63900415]
 [-115.09207754   91.36367467]]

Yi
 [[ 2.]
 [ 4.]
 [-3.]
 [-5.]
 [-1.]
 [ 1.]
 [-1.]
 [ 2.]
 [ 5.]
 [ 2.]]

Jacobian
 [[ 8.02523408e+01 -1.66404109e+03  1.00000000e+00  0.00000000e+00]
 [ 2.080361

libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
using driver i915 for 74
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
using driver i915 for 74
pci id for fd 74: 8086:a7a0, driver iris
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
Using DRI3 for screen 0


Number of points used for image 0:  (1003,)
Number of points used for image 1:  (640,)
Number of points used for image 2:  (2818,)
Number of points used for image 3:  (725,)
Number of points used for image 4:  (4752,)

BEST SHIFT VECTOR =  1 4

BEST SSD for image 0 =  24.801712077370944

BEST SHIFT VECTOR =  -4 -5

BEST SSD for image 1 =  15.115889809591991

BEST SHIFT VECTOR =  -2 1

BEST SSD for image 2 =  120.73206913655527

BEST SHIFT VECTOR =  -1 3

BEST SSD for image 3 =  11.737765854194006

BEST SHIFT VECTOR =  4 2

BEST SSD for image 4 =  55.93235610806634

Correction vectors:
 [[ 1.  4.]
 [-4. -5.]
 [-2.  1.]
 [-1.  3.]
 [ 4.  2.]]

Base of correction vectors: 
 [[ -51.76370887  -71.40378863]
 [  32.2234375    42.1671875 ]
 [  54.85628105  -73.86053939]
 [   7.2262069   -76.61517241]
 [-114.66835017   91.35521886]]

Yi
 [[ 1.]
 [ 4.]
 [-4.]
 [-5.]
 [-2.]
 [ 1.]
 [-1.]
 [ 3.]
 [ 4.]
 [ 2.]]

Jacobian
 [[ 7.98474018e+01 -1.69584769e+03  1.00000000e+00  0.00000000e+00]
 [ 2.11976

libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
using driver i915 for 74
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
using driver i915 for 74
pci id for fd 74: 8086:a7a0, driver iris
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/daniel-choate/.drirc: No such file or directory.
Using DRI3 for screen 0


### Plot newest guess

In [ ]:
# # PLOTTING THE NEW SCENE MOSAIC

# # Use open3d to create point cloud visualization 
# # Create visualization 
# vis = o3d.visualization.Visualizer()
# vis.create_window(window_name="Mosaic scene with satellite reference")

# # Create axes @ origin
# axis_origin = o3d.geometry.TriangleMesh.create_coordinate_frame(size=40)

# # Create point cloud for image points
# im0_cloud = o3d.geometry.PointCloud()
# im0_cloud.points = o3d.utility.Vector3dVector(gnav.im_pts_best_guess[0]['pts'])
# im0_cloud.colors = o3d.utility.Vector3dVector(gnav.im_mosaic[0]['color_g'])

# # Create point cloud for image points
# im1_cloud = o3d.geometry.PointCloud()
# im1_cloud.points = o3d.utility.Vector3dVector(gnav.im_pts_best_guess[1]['pts'])
# im1_cloud.colors = o3d.utility.Vector3dVector(gnav.im_mosaic[1]['color_g'])

# # Create point cloud for image points
# im2_cloud = o3d.geometry.PointCloud()
# im2_cloud.points = o3d.utility.Vector3dVector(gnav.im_pts_best_guess[2]['pts'])
# im2_cloud.colors = o3d.utility.Vector3dVector(gnav.im_mosaic[2]['color_g'])

# # Create point cloud for image points
# im3_cloud = o3d.geometry.PointCloud()
# im3_cloud.points = o3d.utility.Vector3dVector(gnav.im_pts_best_guess[3]['pts'])
# im3_cloud.colors = o3d.utility.Vector3dVector(gnav.im_mosaic[3]['color_g'])

# # Create point cloud for image points
# im4_cloud = o3d.geometry.PointCloud()
# im4_cloud.points = o3d.utility.Vector3dVector(gnav.im_pts_best_guess[4]['pts'])
# im4_cloud.colors = o3d.utility.Vector3dVector(gnav.im_mosaic[4]['color_g'])

# # Create point cloud for reference cloud (satellite)
# ref_cloud = o3d.geometry.PointCloud()
# ref_cloud.points = o3d.utility.Vector3dVector(gnav.ref_pts)
# ref_cloud.colors = o3d.utility.Vector3dVector(gnav.ref_rgb)

# # Add necessary geometries to visualization 
# vis.add_geometry(axis_origin)
# vis.add_geometry(im0_cloud)
# vis.add_geometry(im1_cloud)
# vis.add_geometry(im2_cloud)
# vis.add_geometry(im3_cloud)
# vis.add_geometry(im4_cloud)
# vis.add_geometry(ref_cloud)

# # # Size options (jupyter gives issues when running this multiple times, but it looks better)
# # render_option = vis.get_render_option()
# # render_option.point_size = 2



# # Run and destroy visualization 
# vis.run()
# vis.destroy_window()

# PLOTTING TOOLS 

In [ ]:
# # Plot and visualize SSD values (was originally used in LSquares Loop 

# # Create a 5x5 grid of x and y coordinates
# x = np.linspace(-n, n, 2*n+1)
# y = np.linspace(-n, n, 2*n+1)
# Y, X = np.meshgrid(x, y)
# # print(ssds)

# # print(x)
# # print(X)
# # print(Y)
# i = 1
# # Best shift
# idrow, idcol = np.unravel_index(np.argmin(SSDS_CURR[i]), ssds.shape)
# print(idrow, idcol)
# shiftx_min = idrow-n
# shifty_min = idcol-n
# # print("BEST SHIFT = ", shiftx_min, shifty_min)
# # print("BEST SSD = ", SSDS_CURR[i][idrow, idcol])

# # PLOTTING A SINGLE VECTOR FIELD FOR SSD
# # Create the figure and 3D axis
# %matplotlib qt
# fig = plt.figure()
# ax = fig.add_subplot(111, projection='3d')

# # Plot the 3D vectors
# ax.quiver(X, Y, np.zeros_like(SSDS_CURR[i]), np.zeros_like(SSDS_CURR[i]), np.zeros_like(SSDS_CURR[i]), (SSDS_CURR[i]/1000)**2, arrow_length_ratio=0.1)

# # Set axis limits
# ax.set_xlim([-11, 11])  # X axis range
# ax.set_ylim([-11, 11])  # Y axis range
# ax.set_zlim([0, (np.max(SSDS_CURR[i]) / 1000)**2])  # Z axis range, adjust based on your data

# # Labels and title
# ax.set_xlabel('X')
# ax.set_ylabel('Y')
# ax.set_zlabel('Z')
# ax.set_title('Pixel Correction Vector Field')